### PR TITLE
Tokio crate port

### LINKED ISSUE #8: Make tokio-serial compatible with "reformed" tokio usage
I think this mainly means tokio-serial should accept a tokio::reactor::Handle and stop using tokio_core and tokio_io.

### PR DESCRIPTION
**Pull request by lnicola**
Fixes #8. Untested.

I'm not sure about the `poll_{read,write}` changes, can you take a look?

### CODE REVIEW

**Comment by berkowski** [comment]
Just getting around to this now.  I tried running the `serial_println` with a serial spitter and don't see anything coming up in the terminal.  I don't think this is necessarily a problem with this PR, as I don't see anything with the master-branch either, but would you confirm?

**Comment by lnicola** [comment]
I couldn't test this PR, sorry. I have a small program which uses a serial port, so I could try porting that to `tokio` and seeing if everything works.

**Comment by berkowski** [comment]
Yeah, I suspect there's something going on either in the underlying `mio-serial` or even `serialport-rs` (though I doubt it's the latter).

I'm going to leave this PR open while I slowly poke at the root cause of things.

**Comment by lnicola** [comment]
I guess my `poll_read` and `AsyncRead` are bogus. The trait has changed, but I don't know how the old one used to work.

**Comment by ndusart** [comment]
I tried on the `master` branch (using `mio-serial` 0.8 and adding `try_clone` function) so without the new `tokio` crate and this is the same behaviour (only polled once at creation of the stream, and nothing afterwards) :worried: 

So, it shouldn't be your `AsyncRead` implementation that makes that problem.

**Comment by ndusart** [comment]
Trying the example in the history of the repository and it stops functioning at the commit 12d02f69c5e1ab949be088785ca3c719cca01989

You shouldn't unwrap the `PollEvented` to get the inner `Read + Write` for implementing `Read` and `Write` traits because it is in the `PollEvented` implementation that all the readiness registration is made.

I tested on this PR by reverting this commit and it works ! :)

**Comment by lnicola** [comment]
@ndusart Do you mean like in my last commit?

**Comment by lnicola** [comment]
So it's working now, but do `poll_{read,write}" do anything? They should now be part of the `Async{Read,Write}` traits, but they return a different error type, so they can't.

**Comment by berkowski** [comment]
Yup, working for me too after the revert.

@ndusart , thanks for your help as always!  Just to make sure I understand your comment; I shouldn't have been calling the `get_mut()` on the `PollEvented2` io objects for the `io::Read` and `io::Write` implementations because `PollEvented2` itself implements `Read` and `Write`, correct?  Which is how Inicola has changed it to.

@lnicola , thanks for the continued work on the PR.  I think you're correct about the `poll_*` methods belonging in `AsyncRead` and `AsnycWrite` traits.  I can either merge the PR as is, since it does reflect a major improvement, or hold off if you'd like to keep poking at things.

**Comment by lnicola** [comment]
I just realized I was mistaken about the `Error` types. I added a commit for those two methods, but I still have no idea how this implementation is different from the default one. My app still seems to be working, so there's that.

**Comment by berkowski** [comment]
I don't think they differ at all.  Like ndusart's comment on the implementation of `io::Read`, since the wrapped io member implements `PollEvented2` it also implements `AsyncRead` and `AsyncWrite` and we can just call the wrapped version.

**Comment by lnicola** [comment]
But calling the inner methods still seems a little "more direct". So maybe it's okay to leave it like this, unless you think otherwise.

And to answer, I have no other planned changes.

**Comment by berkowski** [comment]
I wouldn't try to be the gauge of "correctness" here :)  Especially with my rust-fu falling a bit out of date lately.

I'm going to go ahead and merge the PR and try to cut a 0.8 release for crates.io before I need to go offline again due to work for a bit again.  Thank you again for the work and patience!

**Comment by ndusart** [comment]
Yes that's it. Calling `get_mut()` unwraps the inner object and bypasses the `PollEvented` implementation.

**Comment by lnicola** [comment]
Make that 0.7, as it wasn't released yet. Ouch, I just realized there was a changelog.

**Comment by berkowski** [comment]
I'll be skipping 0.7 for `tokio-serial`.  I'm trying, if possible, to keep `tokio-serial` and `mio-serial` at the same minor revision, and I didn't get around to fixing the tokio layer for `mio-serial` 0.7 :( 

No worries about the changelog -- updating it now.

**Comment by ndusart** [comment]
About the `poll_*` functions, we do not have to implement them, they are provided by the `AsyncRead` and `AsyncWrite` traits. So we can just remove them without moving them into an `Async*` impls.

But it does not matter much as all versions are functionally equivalents.

**Pull request merged**
