### PR TITLE
Apply suggestions from @emgre

### PR DESCRIPTION
**Pull request by ColinFinck**
This PR removes the mio-serial dependency and uses `ManuallyDrop` to prevent freeing the Win32 handle twice. Both are suggestions by @emgre in https://github.com/berkowski/tokio-serial/pull/39#issuecomment-879349001

What is left is a clean separation between the Unix and Windows implementations, which I would consider release-worthy.
Looking forward to your reviews @berkowski, @emgre

### CODE REVIEW

**Comment by berkowski** [comment]
There's a lot going on in this PR.  I'm initially wary of the code duplication to get the file descriptor in an async mode from `mio-serial` combined with dropping the dependency.  I'd rather that low-level stuff be specified one place so changes can be made in one spot if there's a problem.

I'm adding FromRawHandle/ToRawHandle impl's to mio-serial now with the idea of opening the serial port there, letting mio-serial do the os-specific async calls, then rip the RawHandle out to use with tokio's NamedPipe structs.  If it works it will keep the code duplication down to a minimum.  If it doesn't then we can try moving ahead with this.

**Comment by berkowski** [comment]
I've pushed a new `dev/FromRawHandle` branch (a0c1cdd).  It's compiling but I don't have time to test it just now.

**Comment by ColinFinck** [comment]
@berkowski You are right, `AsRawHandle` in `mio-serial` is everything we need to fully leverage it for the low-level part without duplicating code.
I've reintroduced the `mio-serial` dependency in this PR and removed a lot of duplicate code.
The final result looks even cleaner.

Please have another look if this PR can be merged.
Apart from the double-free fix, it also comes with:
* Working `Read` and `Write` implementations for Windows. It turned out to be possible after all using `try_read` and `try_write` from `NamedPipeClient`. They may fail with `ErrorKind::WouldBlock`, but that's still better than nothing.
* `available_ports` exported (wanted in #28)
* `AsRawHandle` for `tokio_serial::SerialStream` (now that it has proven to be useful)

I have tested my PR under Windows and Linux.

**Comment by berkowski** [comment]
@ColinFinck Could you give the current tip of `dev/FromRawHandle` a try to see if it works for you?  It passed a simple test for me this morning and has most of these changes already in a slightly cleaner format.

**Comment by ColinFinck** [comment]
It works either way. I disagree that having both the Unix and Windows implementations in a single file is considered cleaner though. The differences grew substantial enough to warrant distinct implementations in "unix.rs" and "windows.rs". This also reduces the total number of required `#[cfg(unix)]` / `#[cfg(windows)]` conditional compilations.

In fact, I was inspired by your [mio-serial at revision 38a3778](https://github.com/berkowski/mio-serial/tree/38a3778324da5e312cfb31402bd89e52d0548a4c/src) while developing this PR. It also comes with "unix.rs" and "windows.rs" and imports the platform-specific serial ports as `NativeBlockingSerialPort`, just like my `NativeSerialStream` does.

I'm therefore asking you to reconsider my PR. Most of the changed lines actually just move code to new files without changing it.
I could squash/amend commits if that makes reviewing easier.

**Comment by berkowski** [comment]
berkowski/mio-serial@38a3778324da actually moves away from the windows/posix module files (they're not listed in `lib.rs`, you can remove both files and the crate will compile).  I still have to remove `unix.rs` in `mio-serial` and I would remove `windows.rs` here under this pattern.

I can no longer find my paper notes but I believe I modeled my own change after Tokio's structure.  See https://docs.rs/tokio/1.8.1/src/tokio/net/tcp/stream.rs.html for example, though that's newer than any source I would have used at the time.  I'm pretty sure this is the case though, as there's at least one 'TcpStream' typo still in the current docstrings.  However, I don't have quite as clean an abstraction so there's a bit more more `#[cfg()]` cruft but I don't think it's an unreasonable amount.

I feel the benefit of this strategy stems from most of the internal machinery is just getting to some underlying object and calling the same-named method on it and using `#[cfg] blocks` can reduce many of these to single points of contact.

**Comment by ColinFinck** [comment]
Well, `TcpStream` is integrated into `tokio` itself and can therefore use `PollEvented` to actually write platform-agnostic code without `#[cfg]` blocks. I wish we had the same option, but this has to wait until `mio` gets stable.
Until then, we need many more `#[cfg]` blocks than `TcpStream`, and I wanted to reduce that number through separate Unix and Windows implementations. This has zero overhead after all, as the Rust compiler inlines such crate-private structs and method calls into the public `tokio_serial::SerialStream` interface (and likely even beyond with LTO).

Anyway, the most important thing is moving forward with the 4.4/5.0 release either way. I'd be fine if you merged your `dev/FromRawHandle`, and I integrate my missing changes in a subsequent PR. Or you just merge this PR and we would be done.

**Comment by berkowski** [comment]
I'm going to merge it to reflect the work you've put in which I feel should be attributed, but I'm going to keep the layout from the `dev/FromRawHandle` branch.  I feel like that's a good compromise

**Pull request merged**
